### ISSUE TITLE
Add exclusions file to filter validations produced by the COP 

### ISSUE THREAD

**Issue by bmazzarol** [bmazzarol/atom-plsql-linter#2]
Allow the user to create a root project file called plsql-linter.json with the correct structure, to be passed to the plsql-lint server to filter the validation messages produced on lint.

See bmazzarol/plsql-lint-server#2 for more information.

**Comment by tschf** [comment]
I was thinking about this yesterday. Maybe `.oraclelint.json`? Since it relates to the Oracle database, not necessarily plsql code (sql for example). Also, the `.` at the front of the file so it comes hidden (and seems to be how all the other linters operate).

I also had the thought that this would be more of a client side operation. e.g.:

- send request to server
- get list of errors back
- read the lint config (whatever it'll be named)
- remove any errors that match to the supplied exclusion filter
- send updated error array to lint engine

Keeps the server simple, and as the lint config evolves, doesn't require updates to two moving pieces. 

Maybe the data the server sends back doesn't support this? Haven't really looked into it in great detail yet, but just a thought :)

**Comment by tschf** [comment]
Also, maybe a configuration for a path to a global config and/or just expecting one at `$HOME/.plsql-lint` (or whatever you end up going with) that will be read and merged with the one supplied in the project root. This will be if there is a constant set of filters you want applied to all projects.

Maybe you've thought of this, I saw on the server side you have the param: `@param includeGlobal` .. maybe that relates to that?

**Comment by bmazzarol** [comment]
All good points.

Using the hidden file name standard is a good idea and the global default file also a good idea.

The operations can be done purely on the client side and would be better for upgrading clients against differing version of the server component. The only consideration I have with the server is that it could be reused with additional text editors, adding in the additional complexity was not much of an issue. 

The global override related to how global filters that are not scoped to a given file path are included. The idea was that you setup a global filters, then you can override that on a file by file basis, the includeGlobal flag would then be used to indicate if the override includes the filters set in global, or excludes them.

Structured as follows,

`[
    {// global filters, not scoped to any file the first of these will be used if more than one is configured
       "codes": ["G-0000"] // codes to filter
    },
    { // file specific filters
        "path":"some/file/path/test.sql" // relative editor file path
        "codes": ["G-12345"] // codes to filter
        "includeGlobal: false // defaults to true
    }
]`

So for all files not 'some/file/path/test.sql' G-0000 will be filtered, and for 'some/file/path/test.sql' G-12345 will be filtered. If includeGlobal was true then both G-0000 and G-12345 would be filtered for 'some/file/path/test.sql'.

I think that a global non-project config file is a great idea, Just need to decide on a merge strategy. 

I was also thinking that adding file exclusions would be a good idea. This would be a purely client side feature.
